In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
df = pd.read_csv('cleaned_data.csv')
df.shape

C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(184224, 29)

In [3]:
df.head()

,Highway number,Accident cause,Accident classfication,Weekday,Climate,Moment of the day,Injured,Number of light injured,Number of people without info,Number of people not harmed,...,Road type,Road layout,State,Soil use,Total cars,Hour,Year,Month,Day,target
0,376.0,Nature Phenomena ...,Injured Victims,Sunday,Rain,Night,1,0,0,0,...,Simple,Straight,PR,No,1,0,2017,1,1,1
1,101.0,Lack of Attention to Driving ...,No Victims,Sunday,Rain,Night,0,0,0,1,...,Double,Curve,SC,No,1,0,2017,1,1,0
2,153.0,Animal in the road ...,Injured Victims,Sunday,Drizzle,Night,2,2,0,0,...,Simple,Straight,PR,No,1,0,2017,1,1,1
3,153.0,Problems on the tire ...,Injured Victims,Sunday,Clear sky,Night,1,0,0,0,...,Double,Straight,GO,Yes,1,0,2017,1,1,1
4,280.0,Alcohol ingestion ...,Injured Victims,Sunday,Rain,Night,1,1,0,0,...,Simple,Not Available,SC,No,1,0,2017,1,1,1

In [4]:
from sklearn.preprocessing import LabelEncoder 
  
le = LabelEncoder() 
  
df['Accident cause']= le.fit_transform(df['Accident cause'].astype(str)) 
df['Accident classfication']= le.fit_transform(df['Accident classfication'].astype(str)) 
df['Climate']= le.fit_transform(df['Climate'].astype(str)) 
df['Weekday']= le.fit_transform(df['Weekday']) 
df['Moment of the day']= le.fit_transform(df['Moment of the day'].astype(str)) 
df['city']= le.fit_transform(df['city'].astype(str)) 
df['regional']= le.fit_transform(df['regional'].astype(str)) 
df['Road way']= le.fit_transform(df['Road way'].astype(str)) 
df['Accident type']= le.fit_transform(df['Accident type'].astype(str)) 
df['Road type']= le.fit_transform(df['Road type'].astype(str))
df['Road layout']= le.fit_transform(df['Road layout'].astype(str)) 
df['State']= le.fit_transform(df['State'].astype(str))
df['Soil use']= le.fit_transform(df['Soil use'].astype(str))

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184224 entries, 0 to 184223
Data columns (total 29 columns):
Highway number                   184078 non-null float64
Accident cause                   184224 non-null int32
Accident classfication           184224 non-null int32
Weekday                          184224 non-null int32
Climate                          184224 non-null int32
Moment of the day                184224 non-null int32
Injured                          184224 non-null int64
Number of light injured          184224 non-null int64
Number of people without info    184224 non-null int64
Number of people not harmed      184224 non-null int64
Kilometer                        184078 non-null object
latitude                         89518 non-null float64
longitude                        89518 non-null float64
Deaths                           184224 non-null int64
city                             184224 non-null int32
Total people                     184224 non-null int64
regional                         184224 non-null int32
Road way                         184224 non-null int32
Accident type                    184224 non-null int32
Road type                        184224 non-null int32
Road layout                      184224 non-null int32
State                            184224 non-null int32
Soil use                         184224 non-null int32
Total cars                       184224 non-null int64
Hour                             184224 non-null int64
Year                             184224 non-null int64
Month                            184224 non-null int64
Day                              184224 non-null int64
target                           184224 non-null int64
dtypes: float64(3), int32(13), int64(12), object(1)
memory usage: 31.6+ MB

In [6]:
df.head()

,Highway number,Accident cause,Accident classfication,Weekday,Climate,Moment of the day,Injured,Number of light injured,Number of people without info,Number of people not harmed,...,Road type,Road layout,State,Soil use,Total cars,Hour,Year,Month,Day,target
0,376.0,23,1,7,15,5,1,0,0,0,...,4,9,17,0,1,0,2017,1,1,1
1,101.0,18,2,7,15,5,0,0,0,1,...,0,3,23,0,1,0,2017,1,1,0
2,153.0,4,1,7,5,5,2,2,0,0,...,4,9,17,0,1,0,2017,1,1,1
3,153.0,26,1,7,2,5,1,0,0,0,...,0,9,8,3,1,0,2017,1,1,1
4,280.0,2,1,7,15,5,1,1,0,0,...,4,5,23,0,1,0,2017,1,1,1

In [7]:
df.to_csv('road_accident_one_hot_encoding_conversion.csv')